version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  python_app:
    build: .
    container_name: python_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_DB_HOST: mongodb://mongo:27017/

volumes:
  mongo_data:
