version: '3.8'
services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto_container
    ports:
      - "1883:1883"
      - "9001:9001"
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ./mosquitto/config/password.txt:/mosquitto/config/password.txt
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mqtt_debugger:
    image: eclipse-mosquitto:latest
    command: /bin/sh -c "mosquitto_sub -h mosquitto_container -t '#' -v -u 'user' -P 'password'"
    depends_on:
      - mosquitto

  python_app:
    build: .
    container_name: python_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - mosquitto
    environment:
      MONGO_DB_HOST: mongodb://mongo:27017/
      MQTT_BROKER: mosquitto
      MQTT_PORT: 1883
      MQTT_USER: user
      MQTT_PASSWORD: password

volumes:
  mongo_data:
