# This workflow will install Python dependencies and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test python code

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - name: Lint and format with pre-commit
        run: |
          pre-commit run --all-files

      - name: Mongodb service
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: '4.2'
          mongodb-replica-set: test-rs
          mongodb-port: 27017

      - name: Test with unittest
        env:
          MONGO_DB_HOST: mongodb://localhost:27017/
        run: |
          pytest
